### ISSUE TITLE
Modules suggestion

### ISSUE THREAD

**Issue by parkjunmin** [runtimeterrorist/tgsint-bot#2]
https://www.criminalip.io/ - Criminal IP is a specialized Cyber Threat Intelligence (CTI) search engine that allows users to search for various security-related information such as malicious IP addresses, domains, banners, etc. It can be widely integrated

**Comment by bugourmet** [comment]
Thanks for the suggestion. 
Will take a look on the API documentation and consider adding it in future "release"

**Comment by parkjunmin** [comment]
Thanks, Bro
